version: '3.8'

services:
  # 1. RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - campus-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. MySQL Database (Untuk SIAKAD)
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: siakad
    ports:
      - "3307:3306"  # Port digeser ke 3307 agar tidak bentrok dengan XAMPP/Local
    networks:
      - campus-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 3. PostgreSQL Database (Untuk Keuangan)
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keuangan
    ports:
      - "5433:5432"  # Port digeser ke 5433 agar tidak bentrok dengan Local
    networks:
      - campus-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 4. SIAKAD Microservice
  siakad:
    build:
      context: ./siakad
      dockerfile: Dockerfile
    container_name: siakad
    ports:
      - "8001:8001"
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - campus-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy

  # 5. Finance Microservice
  finance:
    build:
      context: ./keuangan
      dockerfile: Dockerfile
    container_name: finance
    ports:
      - "8002:8002"
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - campus-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  # 6. Library Microservice
  library:
    build:
      context: ./library
      dockerfile: Dockerfile
    container_name: library
    ports:
      - "8003:8003"
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - campus-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  # 7. Attendance Microservice
  attendance:
    build:
      context: ./attendance
      dockerfile: Dockerfile
    container_name: attendance
    ports:
      - "8004:8004"
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - campus-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  # 8. Nginx API Gateway
  nginx-gateway:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-gateway
    ports:
      - "8000:8000"
    networks:
      - campus-network
    depends_on:
      - siakad
      - finance
      - library
      - attendance
      - integration-layer

  # 9. Integration Layer (Router & Adapter)
  integration-layer:
    build:
      context: ./integration-layer
      dockerfile: Dockerfile
    container_name: integration-layer
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - campus-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "0:80"
    networks:
      - campus-network

# Bagian Networks Utama
networks:
  campus-network:
    driver: bridge

# Bagian Volumes Utama (Penyimpanan Permanen)
volumes:
  rabbitmq_data:
  mysql_data:
  postgres_data: